// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYcJntajgt7H9ea2rZqxgtQK9su4Nbck8',
    appId: '1:949555798833:web:7c3660e0db0a3aad7a8610',
    messagingSenderId: '949555798833',
    projectId: 'bookstoretest2025',
    authDomain: 'bookstoretest2025.firebaseapp.com',
    storageBucket: 'bookstoretest2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAovnQr_Jj_Vczw49-cVd2tIYKP4RFTvhY',
    appId: '1:949555798833:android:7386b709ce02bbde7a8610',
    messagingSenderId: '949555798833',
    projectId: 'bookstoretest2025',
    storageBucket: 'bookstoretest2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN7q6PihrkhzTipPgOlmT9vJTVpewzg2I',
    appId: '1:949555798833:ios:077d04e2e437c70f7a8610',
    messagingSenderId: '949555798833',
    projectId: 'bookstoretest2025',
    storageBucket: 'bookstoretest2025.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN7q6PihrkhzTipPgOlmT9vJTVpewzg2I',
    appId: '1:949555798833:ios:077d04e2e437c70f7a8610',
    messagingSenderId: '949555798833',
    projectId: 'bookstoretest2025',
    storageBucket: 'bookstoretest2025.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYcJntajgt7H9ea2rZqxgtQK9su4Nbck8',
    appId: '1:949555798833:web:2554876d75f492897a8610',
    messagingSenderId: '949555798833',
    projectId: 'bookstoretest2025',
    authDomain: 'bookstoretest2025.firebaseapp.com',
    storageBucket: 'bookstoretest2025.firebasestorage.app',
  );

}